import {
  CardsIcon,
  PlusIcon,
  RabbitIcon,
  RepeatIcon,
  SparkleIcon,
} from "@/app/ui/ph-icon";
import Image from "next/image";
import styles from "./HowItWorks.module.css";

const steps = [
  {
    num: "1.",
    title: "add it",
    desc: "paste any link or upload a pdf, video, or photo of your notes.",
    bg: "/images/img-cloak.jpg",
    overlays: [
      {
        src: "/images/ui-mood.jpg",
        w: 204,
        iw: 731,
        ih: 584,
        cls: "ov1",
        alt: "Mood selector in the biu app",
      },
      {
        src: "/images/ui-energy-slider.jpg",
        w: 199,
        iw: 1233,
        ih: 377,
        cls: "ov2",
        alt: "Study energy slider in the biu app",
      },
    ],
  },
  {
    num: "2.",
    title: "biu breaks it down",
    desc: "a clear summary and a deck of flashcards, generated automatically.",
    bg: "",
    overlays: [
      {
        src: "/images/ui-energy-trend.jpg",
        w: 212,
        iw: 808,
        ih: 645,
        cls: "ov3",
        alt: "Learning progress trend generated by biu",
      },
      {
        src: "/images/ui-sleep.jpg",
        w: 237,
        iw: 797,
        ih: 403,
        cls: "ov4",
        alt: "Daily review schedule in the biu app",
      },
    ],
  },
  {
    num: "3.",
    title: "remember it",
    desc: "biu schedules each card from your review history and increases the interval when you answer correctly.",
    bg: "/images/img-blossoms.webp",
    overlays: [
      {
        src: "/images/ui-routine.jpg",
        w: 300,
        iw: 818,
        ih: 592,
        cls: "ov5",
        alt: "Spaced-repetition study routine in biu",
      },
    ],
  },
];

const tags = [
  { icon: <PlusIcon />, label: "add anything" },
  { icon: <SparkleIcon />, label: "auto summaries" },
  { icon: <CardsIcon />, label: "smart flashcards" },
  { icon: <RepeatIcon />, label: "spaced repetition" },
  { icon: <RabbitIcon />, label: "ai assistant" },
];

export default function HowItWorks() {
  return (
    <section className={styles.section} id="how-it-works">
      <div className={styles.head}>
        <h2 className="h2">three steps, then it sticks forever</h2>
        <p className={styles.sub}>
          biu keeps the loop simple: add your material, let biu break it down,
          and remember it with a daily quiz.
        </p>
      </div>

      <div className={styles.steps}>
        {steps.map((s, index) => (
          <div
            key={s.title}
            className={styles.step}
            data-scroll-reveal
            style={
              {
                "--reveal-delay": `${index * 0.2}s`,
              } as React.CSSProperties
            }
          >
            <div
              className={`${styles.visual} ${!s.bg ? styles.visualPlain : ""}`}
            >
              {s.bg ? (
                <Image
                  alt=""
                  className={styles.visualBackground}
                  fill
                  quality={90}
                  sizes="(max-width: 860px) calc(100vw - 48px), 33vw"
                  src={s.bg}
                />
              ) : null}
              {s.overlays.map((o, i) => (
                <span
                  key={i}
                  className={`${styles.overlay} ${styles[o.cls]}`}
                  style={{ width: o.w }}
                >
                  <Image
                    src={o.src}
                    alt={o.alt}
                    width={o.iw}
                    height={o.ih}
                    sizes={`${o.w}px`}
                  />
                </span>
              ))}
            </div>
            <div className={styles.meta}>
              <h3 className={styles.stepTitle}>{s.title}</h3>
            </div>
            <p className={styles.desc}>{s.desc}</p>
          </div>
        ))}
      </div>

      <div className={styles.tagsWrap}>
        <p className={styles.caption}>small habits, lasting knowledge.</p>
        <div className={styles.tags}>
          {tags.map((t) => (
            <span key={t.label} className={styles.tag}>
              <span className={styles.tagIcon}>{t.icon}</span>
              <span>{t.label}</span>
            </span>
          ))}
        </div>
      </div>
    </section>
  );
}
